driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.2
  - name: fedora-25
    run_list: yum::dnf_yum_compat

suites:
  - name: default
    run_list: test::default
