driver:
  name: dokken
  chef_version: current

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver:
      image: dokken/centos-7
  - name: fedora-latest
    driver:
      image: dokken/fedora-latest

suites:
  - name: default
    run_list: test::default
